

name: render readme

# Controls when the action will run
on:
  push:
    branches: master

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    - uses: r-lib/actions/setup-pandoc@master

    - name: Install package
      run: R CMD INSTALL .
      
    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "badger"))'

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'

    - name: Cache R packages
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: macOS-r-4.0-1-

    - name: commit rendered README
      run: |
        git add README.md man/figures/README-*
        git commit -m "Re-build README.md" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"

